spring:
    data:
        redis:
            host: xx
            port: 6379
            password: xx
            database: 3
            timeout: 3000ms
            lettuce:
                pool:
                    enabled: true
                    min-idle: 1
                    max-wait: 1000ms
                    time-between-eviction-runs: 30s

mybatis-flex:
    datasource:
        okauth-server:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://xx:3306/okauth_server_test
            username: xx
            password: xx
        okauth-permission:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://xx:3306/okauth_permission_test
            username: xx
            password: xx